credentials:
  usernames:
    Proxzy:
      email: parockson@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Prince Rockson 
      password: "1234" # Will be hashed automatically
    prockson:
      email: Proxzy Solution
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Proxy Solution
      password: "Agent0047" # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - parockson@gmail.com