credentials:
  usernames:
    Proxzy:
      email: modumanye@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Michael Odumanye 
      password: "1234" # Will be hashed automatically
    michaelodumanye:
      email: modumanye@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Michael Odumanye
      password: "548494" # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - modumanye@gmail.com